# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: publish

on:
  push:
    tags:
      - '*'

jobs:
  publish:
  
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x    
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Get Tag
      run: echo "TAG_NAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
    - name: Pack
      run: dotnet pack -o artifacts -p:Version=${{env.TAG_NAME}}
    - name: Push
      run: dotnet nuget push artifacts/*.nupkg --api-key secrets.NUGET_API_KEY --source https://api.nuget.org/v3/index.json
